//
// File generated by rootcint at Sun Nov 22 20:22:49 2015

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "pwaFitViewDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void MyMainFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_MyMainFrame(void *p);
   static void deleteArray_MyMainFrame(void *p);
   static void destruct_MyMainFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MyMainFrame*)
   {
      ::MyMainFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MyMainFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MyMainFrame", ::MyMainFrame::Class_Version(), "pwaFitView_Gui.h", 69,
                  typeid(::MyMainFrame), DefineBehavior(ptr, ptr),
                  &::MyMainFrame::Dictionary, isa_proxy, 0,
                  sizeof(::MyMainFrame) );
      instance.SetDelete(&delete_MyMainFrame);
      instance.SetDeleteArray(&deleteArray_MyMainFrame);
      instance.SetDestructor(&destruct_MyMainFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MyMainFrame*)
   {
      return GenerateInitInstanceLocal((::MyMainFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MyMainFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *MyMainFrame::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *MyMainFrame::Class_Name()
{
   return "MyMainFrame";
}

//______________________________________________________________________________
const char *MyMainFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MyMainFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MyMainFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MyMainFrame::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void MyMainFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class MyMainFrame.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void MyMainFrame::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class MyMainFrame.
      TClass *R__cl = ::MyMainFrame::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fMenuBar", &fMenuBar);
      R__insp.Inspect(R__cl, R__parent, "*fMenuDock", &fMenuDock);
      R__insp.Inspect(R__cl, R__parent, "*fECanvas", &fECanvas);
      R__insp.Inspect(R__cl, R__parent, "*fListWBox", &fListWBox);
      R__insp.Inspect(R__cl, R__parent, "*fListFBox", &fListFBox);
      R__insp.Inspect(R__cl, R__parent, "*fYieldButton", &fYieldButton);
      R__insp.Inspect(R__cl, R__parent, "*fPhaseButton", &fPhaseButton);
      R__insp.Inspect(R__cl, R__parent, "*fLikelyButton", &fLikelyButton);
      R__insp.Inspect(R__cl, R__parent, "*fBWButton", &fBWButton);
      R__insp.Inspect(R__cl, R__parent, "*fAWFButton", &fAWFButton);
      R__insp.Inspect(R__cl, R__parent, "*MassTextBox", &MassTextBox);
      R__insp.Inspect(R__cl, R__parent, "*WidthTextBox", &WidthTextBox);
      R__insp.Inspect(R__cl, R__parent, "*AmpTextBox", &AmpTextBox);
      R__insp.Inspect(R__cl, R__parent, "*FHSlider", &FHSlider);
      R__insp.Inspect(R__cl, R__parent, "*fWSelected", &fWSelected);
      R__insp.Inspect(R__cl, R__parent, "*fFSelected", &fFSelected);
      R__insp.Inspect(R__cl, R__parent, "*fFitResults", &fFitResults);
      R__insp.Inspect(R__cl, R__parent, "SaveAsFile", (void*)&SaveAsFile);
      ::ROOT::GenericShowMembers("TGFileInfo", (void*)&SaveAsFile, R__insp, strcat(R__parent,"SaveAsFile."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fCurrentCanvas", &fCurrentCanvas);
      R__insp.Inspect(R__cl, R__parent, "fNumberCanvases", &fNumberCanvases);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_MyMainFrame(void *p) {
      delete ((::MyMainFrame*)p);
   }
   static void deleteArray_MyMainFrame(void *p) {
      delete [] ((::MyMainFrame*)p);
   }
   static void destruct_MyMainFrame(void *p) {
      typedef ::MyMainFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::MyMainFrame

/********************************************************
* pwaFitViewDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablepwaFitViewDict();

extern "C" void G__set_cpp_environmentpwaFitViewDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("pwaFitView_Gui.h");
  G__cpp_reset_tagtablepwaFitViewDict();
}
#include <new>
extern "C" int G__cpp_dllrevpwaFitViewDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MyMainFrame */
static int G__pwaFitViewDict_434_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MyMainFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 6
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MyMainFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (PwaFitResults*) G__int(libp->para[4]), (char*) G__int(libp->para[5]));
   } else {
     p = new((void*) gvp) MyMainFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (PwaFitResults*) G__int(libp->para[4]), (char*) G__int(libp->para[5]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->DoExit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->DoSelect();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->HandleButtons();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->PrintSelected();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->PlotSelected();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->PlotYield((TList*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->PlotPhase((TList*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->PlotLikely();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->PlotBW();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->AddWaveFiles();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->DoSlider();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->AddFileWaves();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->SaveSelected((TList*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->Save();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->ClearSelectedWaves();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->ClearSelectedFiles();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->HandleMenu((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->SetCanvasDivision((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((MyMainFrame*) G__getstructoffset())->CurrentCanvas());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->SendMsg((char*) G__int(libp->para[0]), (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MyMainFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MyMainFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MyMainFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyMainFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__pwaFitViewDict_434_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyMainFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MyMainFrame G__TMyMainFrame;
static int G__pwaFitViewDict_434_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MyMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MyMainFrame*) (soff+(sizeof(MyMainFrame)*i)))->~G__TMyMainFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MyMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MyMainFrame*) (soff))->~G__TMyMainFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MyMainFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncpwaFitViewDict {
 public:
  G__Sizep2memfuncpwaFitViewDict(): p(&G__Sizep2memfuncpwaFitViewDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncpwaFitViewDict::*p)();
};

size_t G__get_sizep2memfuncpwaFitViewDict()
{
  G__Sizep2memfuncpwaFitViewDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancepwaFitViewDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame))) {
     MyMainFrame *G__Lderived;
     G__Lderived=(MyMainFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),G__get_linked_tagnum(&G__pwaFitViewDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),G__get_linked_tagnum(&G__pwaFitViewDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),G__get_linked_tagnum(&G__pwaFitViewDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),G__get_linked_tagnum(&G__pwaFitViewDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),G__get_linked_tagnum(&G__pwaFitViewDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),G__get_linked_tagnum(&G__pwaFitViewDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),G__get_linked_tagnum(&G__pwaFitViewDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablepwaFitViewDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PwaWaveSet>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_vectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_reverse_iteratorlEvectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pwaFitViewDictLN_vectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pwaFitViewDictLN_reverse_iteratorlEvectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pwaFitViewDictLN_vectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MyMainFrame */
static void G__setup_memvarMyMainFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame));
   { MyMainFrame *p; p=(MyMainFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGMenuBar),-1,-1,4,"fMenuBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGDockableFrame),-1,-1,4,"fMenuDock=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TRootEmbeddedCanvas),-1,-1,4,"fECanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGListBox),-1,-1,4,"fListWBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGListBox),-1,-1,4,"fListFBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGRadioButton),-1,-1,4,"fYieldButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGRadioButton),-1,-1,4,"fPhaseButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGRadioButton),-1,-1,4,"fLikelyButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGCheckButton),-1,-1,4,"fBWButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGCheckButton),-1,-1,4,"fAWFButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGTextEntry),-1,-1,4,"MassTextBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGTextEntry),-1,-1,4,"WidthTextBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGTextEntry),-1,-1,4,"AmpTextBox=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGDoubleHSlider),-1,-1,4,"FHSlider=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TList),-1,-1,4,"fWSelected=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TList),-1,-1,4,"fFSelected=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_PwaFitResults),-1,-1,4,"fFitResults=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TGFileInfo),-1,-1,4,"SaveAsFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,67,0,1,-1,-1,-2,4,"fSaveAsFileTypes[14]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fCurrentCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fNumberCanvases=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__pwaFitViewDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarpwaFitViewDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMyMainFrame(void) {
   /* MyMainFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame));
   G__memfunc_setup("MyMainFrame",1078,G__pwaFitViewDict_434_0_1, 105, G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame), -1, 0, 6, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h h - 'UInt_t' 0 - m "
"U 'PwaFitResults' - 0 - fitResults C - - 0 - fitfile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoExit",589,G__pwaFitViewDict_434_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelect",787,G__pwaFitViewDict_434_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleButtons",1339,G__pwaFitViewDict_434_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintSelected",1334,G__pwaFitViewDict_434_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotSelected",1224,G__pwaFitViewDict_434_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotYield",918,G__pwaFitViewDict_434_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - selectedList", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotPhase",912,G__pwaFitViewDict_434_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - selectedList", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotLikely",1033,G__pwaFitViewDict_434_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotBW",568,G__pwaFitViewDict_434_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddWaveFiles",1167,G__pwaFitViewDict_434_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSlider",790,G__pwaFitViewDict_434_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddFileWaves",1167,G__pwaFitViewDict_434_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveSelected",1208,G__pwaFitViewDict_434_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - selectedList", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Save",399,G__pwaFitViewDict_434_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearSelectedWaves",1814,G__pwaFitViewDict_434_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearSelectedFiles",1795,G__pwaFitViewDict_434_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleMenu",993,G__pwaFitViewDict_434_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCanvasDivision",1741,G__pwaFitViewDict_434_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - aRows i - - 0 - aCols", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CurrentCanvas",1343,G__pwaFitViewDict_434_0_20, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SendMsg",689,G__pwaFitViewDict_434_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 0 - Title C - - 0 - Msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__pwaFitViewDict_434_0_22, 85, G__get_linked_tagnum(&G__pwaFitViewDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MyMainFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__pwaFitViewDict_434_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__pwaFitViewDict_434_0_24, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MyMainFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__pwaFitViewDict_434_0_25, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MyMainFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__pwaFitViewDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__pwaFitViewDict_434_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__pwaFitViewDict_434_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__pwaFitViewDict_434_0_31, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyMainFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__pwaFitViewDict_434_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__pwaFitViewDict_434_0_33, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyMainFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~MyMainFrame", 1204, G__pwaFitViewDict_434_0_34, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncpwaFitViewDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalpwaFitViewDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcpwaFitViewDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__pwaFitViewDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGMenuBar = { "TGMenuBar" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGDockableFrame = { "TGDockableFrame" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGDoubleHSlider = { "TGDoubleHSlider" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TGFileInfo = { "TGFileInfo" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_vectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgR = { "vector<PwaWaveSet,allocator<PwaWaveSet> >" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_reverse_iteratorlEvectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PwaWaveSet,allocator<PwaWaveSet> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_PwaFitResults = { "PwaFitResults" , 99 , -1 };
G__linked_taginfo G__pwaFitViewDictLN_MyMainFrame = { "MyMainFrame" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablepwaFitViewDict() {
  G__pwaFitViewDictLN_TClass.tagnum = -1 ;
  G__pwaFitViewDictLN_TBuffer.tagnum = -1 ;
  G__pwaFitViewDictLN_TMemberInspector.tagnum = -1 ;
  G__pwaFitViewDictLN_TObject.tagnum = -1 ;
  G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__pwaFitViewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pwaFitViewDictLN_TList.tagnum = -1 ;
  G__pwaFitViewDictLN_TQObject.tagnum = -1 ;
  G__pwaFitViewDictLN_TGWindow.tagnum = -1 ;
  G__pwaFitViewDictLN_TGObject.tagnum = -1 ;
  G__pwaFitViewDictLN_TGFrame.tagnum = -1 ;
  G__pwaFitViewDictLN_TGCompositeFrame.tagnum = -1 ;
  G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__pwaFitViewDictLN_TGMainFrame.tagnum = -1 ;
  G__pwaFitViewDictLN_TGMenuBar.tagnum = -1 ;
  G__pwaFitViewDictLN_TGCheckButton.tagnum = -1 ;
  G__pwaFitViewDictLN_TGRadioButton.tagnum = -1 ;
  G__pwaFitViewDictLN_TGDockableFrame.tagnum = -1 ;
  G__pwaFitViewDictLN_TGDoubleHSlider.tagnum = -1 ;
  G__pwaFitViewDictLN_TGListBox.tagnum = -1 ;
  G__pwaFitViewDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__pwaFitViewDictLN_TGTextEntry.tagnum = -1 ;
  G__pwaFitViewDictLN_TGFileInfo.tagnum = -1 ;
  G__pwaFitViewDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__pwaFitViewDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__pwaFitViewDictLN_vectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgR.tagnum = -1 ;
  G__pwaFitViewDictLN_reverse_iteratorlEvectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pwaFitViewDictLN_PwaFitResults.tagnum = -1 ;
  G__pwaFitViewDictLN_MyMainFrame.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablepwaFitViewDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TList);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGMenuBar);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGDockableFrame);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGDoubleHSlider);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGListBox);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TGFileInfo);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_vectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgR);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_reverse_iteratorlEvectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pwaFitViewDictLN_PwaFitResults);
   G__tagtable_setup(G__get_linked_tagnum(&G__pwaFitViewDictLN_MyMainFrame),sizeof(MyMainFrame),-1,62464,(char*)NULL,G__setup_memvarMyMainFrame,G__setup_memfuncMyMainFrame);
}
extern "C" void G__cpp_setuppwaFitViewDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuppwaFitViewDict()");
  G__set_cpp_environmentpwaFitViewDict();
  G__cpp_setup_tagtablepwaFitViewDict();

  G__cpp_setup_inheritancepwaFitViewDict();

  G__cpp_setup_typetablepwaFitViewDict();

  G__cpp_setup_memvarpwaFitViewDict();

  G__cpp_setup_memfuncpwaFitViewDict();
  G__cpp_setup_globalpwaFitViewDict();
  G__cpp_setup_funcpwaFitViewDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncpwaFitViewDict();
  return;
}
class G__cpp_setup_initpwaFitViewDict {
  public:
    G__cpp_setup_initpwaFitViewDict() { G__add_setup_func("pwaFitViewDict",(G__incsetup)(&G__cpp_setuppwaFitViewDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initpwaFitViewDict() { G__remove_setup_func("pwaFitViewDict"); }
};
G__cpp_setup_initpwaFitViewDict G__cpp_setup_initializerpwaFitViewDict;

