/********************************************************************
* pwaFitViewDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error pwaFitViewDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablepwaFitViewDict();
extern void G__cpp_setup_inheritancepwaFitViewDict();
extern void G__cpp_setup_typetablepwaFitViewDict();
extern void G__cpp_setup_memvarpwaFitViewDict();
extern void G__cpp_setup_globalpwaFitViewDict();
extern void G__cpp_setup_memfuncpwaFitViewDict();
extern void G__cpp_setup_funcpwaFitViewDict();
extern void G__set_cpp_environmentpwaFitViewDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "pwaFitView_Gui.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__pwaFitViewDictLN_TClass;
extern G__linked_taginfo G__pwaFitViewDictLN_TBuffer;
extern G__linked_taginfo G__pwaFitViewDictLN_TMemberInspector;
extern G__linked_taginfo G__pwaFitViewDictLN_TObject;
extern G__linked_taginfo G__pwaFitViewDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__pwaFitViewDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__pwaFitViewDictLN_TList;
extern G__linked_taginfo G__pwaFitViewDictLN_TQObject;
extern G__linked_taginfo G__pwaFitViewDictLN_TGWindow;
extern G__linked_taginfo G__pwaFitViewDictLN_TGObject;
extern G__linked_taginfo G__pwaFitViewDictLN_TGFrame;
extern G__linked_taginfo G__pwaFitViewDictLN_TGCompositeFrame;
extern G__linked_taginfo G__pwaFitViewDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__pwaFitViewDictLN_TGMainFrame;
extern G__linked_taginfo G__pwaFitViewDictLN_TGMenuBar;
extern G__linked_taginfo G__pwaFitViewDictLN_TGCheckButton;
extern G__linked_taginfo G__pwaFitViewDictLN_TGRadioButton;
extern G__linked_taginfo G__pwaFitViewDictLN_TGDockableFrame;
extern G__linked_taginfo G__pwaFitViewDictLN_TGDoubleHSlider;
extern G__linked_taginfo G__pwaFitViewDictLN_TGListBox;
extern G__linked_taginfo G__pwaFitViewDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__pwaFitViewDictLN_TGTextEntry;
extern G__linked_taginfo G__pwaFitViewDictLN_TGFileInfo;
extern G__linked_taginfo G__pwaFitViewDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__pwaFitViewDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__pwaFitViewDictLN_vectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgR;
extern G__linked_taginfo G__pwaFitViewDictLN_reverse_iteratorlEvectorlEPwaWaveSetcOallocatorlEPwaWaveSetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__pwaFitViewDictLN_PwaFitResults;
extern G__linked_taginfo G__pwaFitViewDictLN_MyMainFrame;

/* STUB derived class for protected member access */
